### ISSUE TITLE
Fehler mit EmergenyDispatch

### ISSUE THREAD

**Issue by Luetscher1312** [FirstWiseman/saltychat-fivem-lua#11]
Grüße,
wir haben mit SaltyChat ein Problem mit EmergencyDispatch. EmergencyDispatch findet export "SetRadioChannel" nicht. 
![Screenshot_248](https://github.com/FirstWiseman/saltychat-fivem-lua/assets/100164326/d7e90ad1-ca54-4827-99b1-d6e811fbe4d1)
![Screenshot_247](https://github.com/FirstWiseman/saltychat-fivem-lua/assets/100164326/8d2eb5f8-e66b-4f5b-8111-8ac9865b7f51)

**Comment by Luetscher1312** [comment]
Weiterer Fehler beim SaltyChat mit EmergencyDispatch. 
[![Uploading Screenshot_217.png…]()](https://media.discordapp.net/attachments/1243549613953257603/1243549614993575966/Emergency.png?ex=6651e154&is=66508fd4&hm=53064d29ba6196afb89e736fceddbf27ab77321749a857bd02d2582e9e649507&=&format=webp&quality=lossless&width=1440&height=572)

**Comment by FirstWiseman** [comment]
Werde es mir anschauen, sobald ich Zeit habe. Sollten weitere Fehler auftreten einfach hier reinschreiben

**Comment by FirstWiseman** [comment]
Export existiert bereits. Einmal probieren Saltychat vor dem emergencydispatch zu starten.

**Comment by Luetscher1312** [comment]
SaltyChat wird vor dem emergencydispatch gestartet
