### ISSUE TITLE
Voice ranges Error

### ISSUE THREAD

**Issue by SirFox1337** [FirstWiseman/saltychat-fivem-lua#4]
For example, if you talk at 8 meters, the person opposite you cannot hear you unless they are also talking at 8 meters.
Same error with other meter ranges

Wenn man zb 8 Meter redet hört die gegenüberstehende Person dich nicht sofern sie nicht ebenfalls auf 8 Metern redet.
Gleicher Fehler bei anderen Meterreichweiten

**Comment by FirstWiseman** [comment]
Ist im neusten release gefixt.
https://github.com/FirstWiseman/saltychat-fivem-lua/releases
