### ISSUE TITLE
EndCall error with Roadphone

### ISSUE THREAD

**Issue by Strandkorb** [FirstWiseman/saltychat-fivem-lua#5]
![VoiceManager](https://github.com/FirstWiseman/saltychat-fivem-lua/assets/166521581/81a6cd46-87cf-4dd1-b8e7-a8e665dcf96c)
![VoiceManager2](https://github.com/FirstWiseman/saltychat-fivem-lua/assets/166521581/dd4cdf8f-09de-44d5-9fee-ccc0af3879e5)

**Comment by FirstWiseman** [comment]
There is already a new Version. And it seems that the Roadphone is sometimes sending no valid Player ServerIds to the EndCall export

**Comment by StateV2023** [comment]
Ist aber immer noch

**Comment by FirstWiseman** [comment]
> Ist aber immer noch
> 
> 

Liegt an Roadphone so wie es aussieht einfach einmal in die Server Konsole schauen ob da Errors kommen das die Spieler Ids "nil" sind

**Comment by StateV2023** [comment]
Wenn man die Nummer einspeichert geht es

**Comment by StateV2023** [comment]
@FirstWiseman ist bei LB phone das gleiche

**Comment by FirstWiseman** [comment]
Hatten das mit lb-phone getestet gehabt, hatten damit keine Probleme, sollte das Problem gefunden werden von eurer Seite aus, dann gerne einmal melden

**Comment by BoltSpace** [comment]
> Hatten das mit lb-phone getestet gehabt, hatten damit keine Probleme, sollte das Problem gefunden werden von eurer Seite aus, dann gerne einmal melden

Ihr habt wie ich annehme, auch die neueste LB-Phone Ressource oder?

**Comment by StateV2023** [comment]
Ja haben die neuste

**Comment by FirstWiseman** [comment]
Ist im neusten Commit gefixt.
