### ISSUE TITLE
Habe denn Bug das die Sprachanzeige im HUD das es nicht auf denn kleinsten Radius ändert

### ISSUE THREAD

**Issue by StateV2023** [FirstWiseman/saltychat-fivem-lua#6]
![Screenshot 2024-04-10 162231](https://github.com/FirstWiseman/saltychat-fivem-lua/assets/166629944/a40af6ec-a611-4a4a-98d9-b8f002957682)

**Comment by FirstWiseman** [comment]
Habe jetzt eine neue Version oben, da bei Lua generell alle Arrays mit dem Index 1 starten, ist alles um 1 verschoben. Ich habe das jetzt geändert und es sollte im neusten release gefixt sein. 
https://github.com/FirstWiseman/saltychat-fivem-lua/releases
